In [1]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "name": [
        "Alice", "Bob", None, "David", "Emma",
        "Frank", "Grace", "Henry", "Isabella", "Jack"
    ],
    "age": [
        22, None, 30, 28, 24,
        35, None, 31, 23, 29
    ],
    "city": [
        "Dhaka", "Chattogram", "Khulna", None, "Sylhet",
        "Barishal", "Rangpur", "Cumilla", None, "Gazipur"
    ],
    "department": [
        "IT", "HR", "Finance", "Marketing", None,
        "IT", "HR", None, "Marketing", "Sales"
    ],
    "salary": [
        45000, 38000, None, 52000, 41000,
        70000, 43000, None, 47000, 55000
    ]
}

In [8]:
df = pd.DataFrame(data)
df

       name   age        city department   salary
0     Alice  22.0       Dhaka         IT  45000.0
1       Bob   NaN  Chattogram         HR  38000.0
2       NaN  30.0      Khulna    Finance      NaN
3     David  28.0         NaN  Marketing  52000.0
4      Emma  24.0      Sylhet        NaN  41000.0
5     Frank  35.0    Barishal         IT  70000.0
6     Grace   NaN     Rangpur         HR  43000.0
7     Henry  31.0     Cumilla        NaN      NaN
8  Isabella  23.0         NaN  Marketing  47000.0
9      Jack  29.0     Gazipur      Sales  55000.0

In [9]:
df.isnull()

    name    age   city  department  salary
0  False  False  False       False   False
1  False   True  False       False   False
2   True  False  False       False    True
3  False  False   True       False   False
4  False  False  False        True   False
5  False  False  False       False   False
6  False   True  False       False   False
7  False  False  False        True    True
8  False  False   True       False   False
9  False  False  False       False   False

In [10]:
df.isnull().sum()

name          1
age           2
city          2
department    2
salary        2
dtype: int64

In [12]:
df["department"]

0           IT
1           HR
2      Finance
3    Marketing
4          NaN
5           IT
6           HR
7          NaN
8    Marketing
9        Sales
Name: department, dtype: str

In [17]:
res = df[df['name']=='Bob']
res

  name  age        city department   salary
1  Bob  NaN  Chattogram         HR  38000.0

In [18]:
df.loc[[4,7]]

    name   age     city department   salary
4   Emma  24.0   Sylhet        NaN  41000.0
7  Henry  31.0  Cumilla        NaN      NaN

In [26]:
df[df.isnull().any(axis = 1)]

       name   age        city department   salary
1       Bob   NaN  Chattogram         HR  38000.0
2       NaN  30.0      Khulna    Finance      NaN
3     David  28.0         NaN  Marketing  52000.0
4      Emma  24.0      Sylhet        NaN  41000.0
6     Grace   NaN     Rangpur         HR  43000.0
7     Henry  31.0     Cumilla        NaN      NaN
8  Isabella  23.0         NaN  Marketing  47000.0

In [36]:
df[df.isnull().any(axis=1)]

       name   age        city department   salary
1       Bob   NaN  Chattogram         HR  38000.0
2       NaN  30.0      Khulna    Finance      NaN
3     David  28.0         NaN  Marketing  52000.0
4      Emma  24.0      Sylhet        NaN  41000.0
6     Grace   NaN     Rangpur         HR  43000.0
7     Henry  31.0     Cumilla        NaN      NaN
8  Isabella  23.0         NaN  Marketing  47000.0

In [37]:
df[df.'city'].isnull().sum()

name          1
age           2
city          2
department    2
salary        2
dtype: int64