In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "name": [
        "Alice", "Bob", None, "David", "Emma",
        "Frank", "Grace", None, "Isabella", "Jack",
        "Liam", "Mia", "Noah", None, "Peter",
        "Queen", "Ryan", "Sophia", "Thomas", None
    ],

    "age": [
        22, None, 30, 28, None,
        35, None, 31, 23, 29,
        27, 26, None, 32, 25,
        None, 34, 24, 28, None
    ],

    "city": [
        "Dhaka", "Dhaka", "Khulna", None, "Sylhet",
        "Dhaka", "Rangpur", "Dhaka", None, "Gazipur",
        "Khulna", None, "Sylhet", "Dhaka", "Gazipur",
        "Khulna", None, "Dhaka", "Sylhet", None
    ],

    "department": [
        "IT", "HR", "Finance", "Marketing", None,
        "IT", "HR", None, "Marketing", "Sales",
        "IT", "Finance", None, "HR", "Marketing",
        "IT", "Finance", None, "Sales", "HR"
    ],

    "salary": [
        45000, 38000, None, 52000, 41000,
        None, 43000, None, 47000, 55000,
        48000, None, 51000, 60000, None,
        72000, 58000, None, 53000, None
    ]
}

In [4]:
df = pd.DataFrame(data)
df

        name   age     city department   salary
0      Alice  22.0    Dhaka         IT  45000.0
1        Bob   NaN    Dhaka         HR  38000.0
2        NaN  30.0   Khulna    Finance      NaN
3      David  28.0      NaN  Marketing  52000.0
4       Emma   NaN   Sylhet        NaN  41000.0
5      Frank  35.0    Dhaka         IT      NaN
6      Grace   NaN  Rangpur         HR  43000.0
7        NaN  31.0    Dhaka        NaN      NaN
8   Isabella  23.0      NaN  Marketing  47000.0
9       Jack  29.0  Gazipur      Sales  55000.0
10      Liam  27.0   Khulna         IT  48000.0
11       Mia  26.0      NaN    Finance      NaN
12      Noah   NaN   Sylhet        NaN  51000.0
13       NaN  32.0    Dhaka         HR  60000.0
14     Peter  25.0  Gazipur  Marketing      NaN
15     Queen   NaN   Khulna         IT  72000.0
16      Ryan  34.0      NaN    Finance  58000.0
17    Sophia  24.0    Dhaka        NaN      NaN
18    Thomas  28.0   Sylhet      Sales  53000.0
19       NaN   NaN      NaN         HR      NaN

In [5]:
df.isnull()

     name    age   city  department  salary
0   False  False  False       False   False
1   False   True  False       False   False
2    True  False  False       False    True
3   False  False   True       False   False
4   False   True  False        True   False
5   False  False  False       False    True
6   False   True  False       False   False
7    True  False  False        True    True
8   False  False   True       False   False
9   False  False  False       False   False
10  False  False  False       False   False
11  False  False   True       False    True
12  False   True  False        True   False
13   True  False  False       False   False
14  False  False  False       False    True
15  False   True  False       False   False
16  False  False   True       False   False
17  False  False  False        True    True
18  False  False  False       False   False
19   True   True   True       False    True

In [6]:
df.isnull().sum()

name          4
age           6
city          5
department    4
salary        7
dtype: int64

In [7]:
df["department"]

0            IT
1            HR
2       Finance
3     Marketing
4           NaN
5            IT
6            HR
7           NaN
8     Marketing
9         Sales
10           IT
11      Finance
12          NaN
13           HR
14    Marketing
15           IT
16      Finance
17          NaN
18        Sales
19           HR
Name: department, dtype: str

In [8]:
res = df[df['name']=='Bob']
res

  name  age   city department   salary
1  Bob  NaN  Dhaka         HR  38000.0

In [9]:
df.loc[[4,7]]

   name   age    city department   salary
4  Emma   NaN  Sylhet        NaN  41000.0
7   NaN  31.0   Dhaka        NaN      NaN

In [10]:
df[df.isnull().any(axis = 1)]

        name   age     city department   salary
1        Bob   NaN    Dhaka         HR  38000.0
2        NaN  30.0   Khulna    Finance      NaN
3      David  28.0      NaN  Marketing  52000.0
4       Emma   NaN   Sylhet        NaN  41000.0
5      Frank  35.0    Dhaka         IT      NaN
6      Grace   NaN  Rangpur         HR  43000.0
7        NaN  31.0    Dhaka        NaN      NaN
8   Isabella  23.0      NaN  Marketing  47000.0
11       Mia  26.0      NaN    Finance      NaN
12      Noah   NaN   Sylhet        NaN  51000.0
13       NaN  32.0    Dhaka         HR  60000.0
14     Peter  25.0  Gazipur  Marketing      NaN
15     Queen   NaN   Khulna         IT  72000.0
16      Ryan  34.0      NaN    Finance  58000.0
17    Sophia  24.0    Dhaka        NaN      NaN
19       NaN   NaN      NaN         HR      NaN

In [11]:
df[df.isnull().any(axis=1)]

        name   age     city department   salary
1        Bob   NaN    Dhaka         HR  38000.0
2        NaN  30.0   Khulna    Finance      NaN
3      David  28.0      NaN  Marketing  52000.0
4       Emma   NaN   Sylhet        NaN  41000.0
5      Frank  35.0    Dhaka         IT      NaN
6      Grace   NaN  Rangpur         HR  43000.0
7        NaN  31.0    Dhaka        NaN      NaN
8   Isabella  23.0      NaN  Marketing  47000.0
11       Mia  26.0      NaN    Finance      NaN
12      Noah   NaN   Sylhet        NaN  51000.0
13       NaN  32.0    Dhaka         HR  60000.0
14     Peter  25.0  Gazipur  Marketing      NaN
15     Queen   NaN   Khulna         IT  72000.0
16      Ryan  34.0      NaN    Finance  58000.0
17    Sophia  24.0    Dhaka        NaN      NaN
19       NaN   NaN      NaN         HR      NaN

In [12]:
df['salary'].isnull().sum()   #for epcific col null check

np.int64(7)

In [13]:
df[df.isnull().any(axis=1)]   #for all row where is null present

        name   age     city department   salary
1        Bob   NaN    Dhaka         HR  38000.0
2        NaN  30.0   Khulna    Finance      NaN
3      David  28.0      NaN  Marketing  52000.0
4       Emma   NaN   Sylhet        NaN  41000.0
5      Frank  35.0    Dhaka         IT      NaN
6      Grace   NaN  Rangpur         HR  43000.0
7        NaN  31.0    Dhaka        NaN      NaN
8   Isabella  23.0      NaN  Marketing  47000.0
11       Mia  26.0      NaN    Finance      NaN
12      Noah   NaN   Sylhet        NaN  51000.0
13       NaN  32.0    Dhaka         HR  60000.0
14     Peter  25.0  Gazipur  Marketing      NaN
15     Queen   NaN   Khulna         IT  72000.0
16      Ryan  34.0      NaN    Finance  58000.0
17    Sophia  24.0    Dhaka        NaN      NaN
19       NaN   NaN      NaN         HR      NaN

In [14]:
df.loc[4].isnull()  #for specific row --> null check

name          False
age            True
city          False
department     True
salary        False
Name: 4, dtype: bool

In [15]:
df.loc[4].isnull().sum()  #same prlm for count

np.int64(2)

In [16]:
df[df['city'] =='Khulna'].isnull()   #for all khulna city null chk

     name    age   city  department  salary
2    True  False  False       False    True
10  False  False  False       False   False
15  False   True  False       False   False

In [20]:
df.isnull().any()   #chk null

name          True
age           True
city          True
department    True
salary        True
dtype: bool